#pragma once

struct Shot_Details {
	short int execution_time;
	short int execution_time_double;
	char parallel_execution;
	short int sound_effect;
	char play_if_outside_screen;
	short int animation;
	char bytes11_30[20];
	char number_of_shots_fired;
	char formation;
	short int firing_parameter1;//interval angle in scatter distance in encircle (hbl);
	short int firing_parameter2;//number of lightning strike columns;
	short int firing_parameter3;//interval between lightning strike columns;
	char target;
	char direction;
	char set_angle_to_target;
	char firing_target;
	short int angle_offset;
	short int angle_offset_double;
	char angle_offset_reverse_rotation_if_facing_right;
	short int angle_dispersion;
	char change_firing_position_according_to_angle;
	char number_of_doubles;
	short int firing_position_offset_x;
	short int firing_position_offset_x_double;
	short int firing_position_offset_y;
	short int firing_position_offset_y_double;
	char firing_position_offset_x_flip_if_facing_right;
	char firing_position_offset_y_flip_if_facing_right;
	short int graphic;
	char z_coordinate;
	char transparency;
	char faction_same_as_user;
	short int faction;
	short int gigantic;
	char movement_type;
	short int movement_type_parameter1;
	short int movement_type_parameter2;
	short int movement_type_parameter3;
	char movement_target;
	char synchronize_with_auto_scroll;
	short int speed;
	short int speed_double;
	char acceleration_enabled;
	short int acceleration;
	short int acceleration_double;
	short int flight_distance;
	char flight_distance_valid;
	short int flight_distance_double;
	char flight_distance_does_not_disappear_at_end;
	char disappearance_time_valid;
	short int disappearance_time;
	short int disappearance_time_double;
	char penetrate_blocks;
	char penetrate_characters;
	char penetrate_block_characters;
	char disappear_on_hitting_shot;
	char value_for_disappearing_on_hitting_shot;
	int power;
	char bytes109_110[2];
	char impact;
	short int effect;
	char acquired_item_palette_type;
	short int acquired_item_palette_number;
	char bytes117_125[9];
	char attack;
	char attack_id;
	char bytes128_143[16];
};

void Read_Shot_Details(struct Shot_Details* details, FILE* read_file);
void Write_Shot_Details(struct Shot_Details* details, FILE* write_file);
